// Generated by Arabiki64 V1.3
// By Buu342


// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_cube[] = {
    {100, 100, 100, 0, 1024, 0, 73, 73, 73, 255}, /* 0 */
    {-100, 100, 100, 0, 2048, 0, -73, 73, 73, 255}, /* 1 */
    {-100, -100, 100, 0, 2048, -1024, -73, -73, 73, 255}, /* 2 */
    {100, -100, 100, 0, 1024, -1024, 73, -73, 73, 255}, /* 3 */
    {100, -100, -100, 0, 0, -1024, 73, -73, -73, 255}, /* 4 */
    {-100, -100, 100, 0, 1024, -2048, -73, -73, 73, 255}, /* 5 */
    {-100, -100, -100, 0, 0, -2048, -73, -73, -73, 255}, /* 6 */
    {-100, -100, -100, 0, 0, 2048, -73, -73, -73, 255}, /* 7 */
    {-100, -100, 100, 0, 1024, 2048, -73, -73, 73, 255}, /* 8 */
    {-100, 100, 100, 0, 1024, 1024, -73, 73, 73, 255}, /* 9 */
    {-100, 100, -100, 0, 0, 1024, -73, 73, -73, 255}, /* 10 */
    {-100, 100, -100, 0, -1024, 0, -73, 73, -73, 255}, /* 11 */
    {100, 100, -100, 0, 0, 0, 73, 73, -73, 255}, /* 12 */
    {-100, -100, -100, 0, -1024, -1024, -73, -73, -73, 255}, /* 13 */
};

static Gfx gfx_cube[] = {
    gsSPVertex(vtx_cube+0, 14, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_MODULATEIDECALA),
    gsDPSetTextureFilter(G_TF_POINT),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPLoadTextureBlock(black_tile, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_MIRROR, G_TX_MIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 3, 5, 0, 4, 5, 6, 0),
    gsSP2Triangles(7, 8, 9, 0, 7, 9, 10, 0),
    gsSP2Triangles(11, 12, 4, 0, 11, 4, 13, 0),
    gsSP2Triangles(12, 0, 3, 0, 12, 3, 4, 0),
    gsSP2Triangles(10, 9, 0, 0, 10, 0, 12, 0),
    gsSPEndDisplayList(),
};

